:experimental:
:toc: 
:toc-title: Service Mesh Demo
:toclevels: 3
:icons: font
:source-highlighter: highlightjs

This repo contains services necessary for demonstrating some of the key features of OpenShift Service mesh.  This was based on material originally found in content generated by Red Hat Developers link:https://github.com/redhat-developer-demos/istio-tutorial[here].  Register for link:http://developers.redhat.com[Red Hat Developers] today!

There are three different and super simple microservices in this system and they are chained together in the following sequence:

```
customer → preference → recommendation
```



== General Setup

To be able to run the walkthrough, you need to follow these steps:

. clone or fork this repo

. open Visual Studio Code with the Remote extension installed

. cd to the local directory

. run the following command
+
----
code .
----
+
. When prompted, indicate that you want to run the folder in a container

. Then follow the demo setup instructions using the VS Code terminal (which will be running in the container)

== Demo Setup

Follow these steps to be able to run link:walkthrough/full-demo-walkthrough.adoc[this walkthrough]:

. First ensure your shell environment is setup correctly
+
----
source scripts/shell-setup.sh
----
+
. Next, run link:scripts/00-service-mesh-cluster-install.sh[00-service-mesh-cluster-install.sh] to start the install process for service mesh on the cluster
+
----
$DEMO_HOME/scripts/00-service-mesh-cluster-install.sh
----
+
. Run link:scripts/01-provision-service-mesh.sh[01-provision-service-mesh.sh] to start up the service mesh control plane (once fully installed)
+
----
$DEMO_HOME/scripts/01-provision-service-mesh.sh
----
+
. Run link:scripts/02-project-no-service-mesh-setup.sh[02-project-no-service-mesh-setup.sh] to create the project with the toy app
+
----
$DEMO_HOME/scripts/02-project-no-service-mesh-setup.sh
----
+
. Run link:scripts/03-project-apply-service-mesh.sh[03-project-apply-service-mesh.sh] to add the toy app to the service mesh
+
----
$DEMO_HOME/scripts/03-project-apply-service-mesh.sh
----
+
. The previous command should only finish once all the containers are up and have their sidecars.  When you look at the pods running the project, it should look something like this:
+
----
$ oc get pods
NAME                                 READY   STATUS    RESTARTS   AGE
customer-6b4cb68cc5-8hdh8            2/2     Running   0          3m25s
customer-v2-584b5c89ff-7lgsb         2/2     Running   0          3m25s
preference-v1-7f4f5dc8dd-4zgj8       2/2     Running   0          2m46s
recommendation-v1-6bbfdf4dfd-9jq69   2/2     Running   0          2m31s
recommendation-v2-754b5cf657-ljtkz   2/2     Running   0          2m31s
----


