:experimental:
:toc: 
:toc-title: Service Mesh Demo
:toclevels: 3
:icons: font
:source-highlighter: highlightjs
:imagesdir: walkthrough/images

This repo contains services necessary for demonstrating some of the key features of OpenShift Service mesh.  This was based on material originally found in content generated by Red Hat Developers link:https://github.com/redhat-developer-demos/istio-tutorial[here].  Register for link:http://developers.redhat.com[Red Hat Developers] today!

There are three different and super simple microservices in this system and they are chained together in the following sequence:

```
customer → preference → recommendation
```



== General Setup

To be able to run the walkthrough, you need to follow these steps:

. clone or fork this repo

. open Visual Studio Code with the Remote extension installed

. cd to the local directory

. run the following command
+
----
code .
----
+
. When prompted, indicate that you want to run the folder in a container

. Then follow the demo setup instructions using the VS Code terminal (which will be running in the container)

== Full Demo Setup

Follow the following steps to be able to run link:walkthrough/walkthrough.adoc[this walkthrough].  These instructions were tested with OpenShift 4.6 and follow the instructions that can be found link:https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/installing-ossm.html[here]

.Component versions included in Red Hat OpenShift Service Mesh version 2.0.0
|===
|Component |Version

|Istio
|1.6.5

|Jaeger
|1.17.7footnote:[This is the current release in the stable channel that gets installed by the script, but you can also select 1.20.0]

|Kiali
|1.24.2

|3Scale Istio Adaptor
|2.0.0

|===

----
$DEMO_HOME/scripts/setup-full-demo.sh
----

The installation takes about 5-10 minutes normally.  If all progressed successfully, you should see a message like this as the script exits:

----
Demo installation progressed successfully!
----

You can then proceed to the link:walkthrough/walkthrough.adoc[Walkthrough].

=== Optional: 3Scale Adaptor Setup (WIP)

WARNING: These instructions are not finished and 3Scale is not officially supported in this demo yet

You can integrate 3Scale into the demo by doing the following after setting up the initial demo

. Install the full demo
. Update the Service Mesh Control Place for demo-app and turn on 3Scale Adaptor
. Install the 3scale per link:https://github.com/tnscorcoran/istio-3scale#3scale-setup-instructions[this section] of instructions with these caveats
** Control plane is already setup.  Don't create a new one.  You have already enabled what is necessary in the previous step
** Whenever the instructions reference `istio-system`, replace this with where your control plane is installed (e.g. `demo-app-istio-system`)
** Don't install the bookinfo app.  Instead we'll apply everything to the demo-app
. Pickup the instructions after the Bookinfo stuff link:https://github.com/tnscorcoran/istio-3scale#apply-3scale-api-management-to-bookinfo[here] to configure 3Scale and Istio with these provisos:
** Whenever the instructions reference `istio-system`, replace this with where your control plane is installed (e.g. `demo-app-istio-system`)
** Instead of labelling the `productpage-v1`, patch all deployments that can be routed to by the istio-gateway in our demo app (i.e. `customer` deployment AND `customer-v2` deployment)
. [red]#Finally, any call you make to the istio system gateway needs to include the `user_key` as specified in the instructions#
** Failure to do so will generate internal `403` errors as the 3scale isito adaptor won't be able to talk to istio
** You can provide this to the loadgen call by using the `-q` flag
+
----
# NOTE: API_KEY assumed to be set to the 3Scale API App associated with the mesh
$DEMO_HOME/scripts/project-load-gen.sh customer --istio -q "user_key=${API_KEY}"
----

== Piecemeal Demo Setup

If you're wanting to take a slower approach toward setting up the ServiceMesh (such as observing the services before they are part of the mesh), then follow the instructions below.

. First ensure your shell environment is setup correctly
+
----
source scripts/shell-setup.sh
----
+
. Next, run link:scripts/00-service-mesh-cluster-install.sh[00-service-mesh-cluster-install.sh] to start the install process for service mesh on the cluster
+
----
$DEMO_HOME/scripts/00-service-mesh-cluster-install.sh
----
+
. Run link:scripts/01-provision-service-mesh.sh[01-provision-service-mesh.sh] to start up the service mesh control plane (once fully installed)
+
----
$DEMO_HOME/scripts/01-provision-service-mesh.sh
----
+
. Run link:scripts/02-project-no-service-mesh-setup.sh[02-project-no-service-mesh-setup.sh] to create the project with the toy app
+
----
$DEMO_HOME/scripts/02-project-no-service-mesh-setup.sh
----
+
. Run link:scripts/03-project-apply-service-mesh.sh[03-project-apply-service-mesh.sh] to add the toy app to the service mesh
+
----
$DEMO_HOME/scripts/03-project-apply-service-mesh.sh
----
+
. The previous command should only finish once all the containers are up and have their sidecars.  When you look at the pods running the project, it should look something like this:
+
----
$ oc get pods
NAME                                 READY   STATUS    RESTARTS   AGE
customer-6b4cb68cc5-8hdh8            2/2     Running   0          3m25s
customer-v2-584b5c89ff-7lgsb         2/2     Running   0          3m25s
preference-v1-7f4f5dc8dd-4zgj8       2/2     Running   0          2m46s
recommendation-v1-6bbfdf4dfd-9jq69   2/2     Running   0          2m31s
recommendation-v2-754b5cf657-ljtkz   2/2     Running   0          2m31s
----

== Appendix

=== Uninstalling the Demo

You can use link:scripts/remove-demo.sh[this script] to remove the demo (and Service Mesh) from the cluster.  

----
$DEMO_HOME/scripts/remove-demo.sh
----

If you want to keep operators installed, use the `-k` flag.  If you are removing a project different from the default `demo-app` use the `-p` flag.

Sometimes a project finalizer can get stuck, in these cases you can re-run the command with the -f flag to force the removal of the project in question.

=== Helpful `istioctl` commands

For general information about istioctl (1.4), see the "Istioldie" documentation link:https://archive.istio.io/v1.4/docs/reference/commands/istioctl/[here]

==== Inspecting a service

You can use the experimental `describe` command to find out more about services in the cluster.  NOTE that you need to specify what the name of the istio system is using the `-i` (istio-system) flag that names the project where the control plane lives.  Assuming you are currently in the project whose control plane you want to describe you could find out about the customer service using this example:

----
$ istioctl -i $(oc project -q)-istio-system x des service customer 
Service: customer
   Port: http 8080/HTTP targets pod port 8080
DestinationRule: customer for "customer"
   Matching subsets: version-v1,version-v2
   No Traffic Policy
Pod is PERMISSIVE, client protocol unspecified
----
