# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: elastic-search
#   namespace: openshift-operators
# spec:
#   channel: preview
#   source: redhat-operators-packages
#   name: elasticsearch-operator
#   sourceNamespace: openshift-operators
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: jaeger
#   namespace: openshift-operators
# spec:
#   channel: stable
#   source: redhat-operators-packages
#   name: jaeger-product
#   sourceNamespace: openshift-operators
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: kiali
#   namespace: openshift-operators
# spec:
#   channel: stable
#   source: redhat-operators-packages
#   name: kiali-ossm 
#   sourceNamespace: openshift-operators
# ---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
 #   startingCSV: servicemeshoperator.v1.1.7