apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: do-not-pass-go
spec:
  compiledAdapter: denier
  params:
    status:
      code: 14
      message: Customer -> Preference -> Recommendation ONLY
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: just-stop
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: no-customer-to-recommendation
spec:
  match: source.labels["app"]=="customer" && destination.labels["app"] == "recommendation" 
  actions:
  - handler: do-not-pass-go
    instances: [ just-stop ]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: no-preference-to-customer
spec:
  match: source.labels["app"]=="preference" && destination.labels["app"] == "customer" 
  actions:
  - handler: do-not-pass-go
    instances: [ just-stop ]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: no-recommendation-to-customer
spec:
  match: source.labels["app"]=="recommendation" && destination.labels["app"] == "customer"
  actions:
  - handler: do-not-pass-go
    instances: [ just-stop ]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: no-recommendation-to-preference
spec:
  match: source.labels["app"]=="recommendation" && destination.labels["app"] == "preference"
  actions:
  - handler: do-not-pass-go
    instances: [ just-stop ]